//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialistMeeting
{
    using System;
    using System.Collections.Generic;
    
    public partial class GtmAlbumLog
    {
        public int GtmAlbumLogId { get; set; }
        public long AlbumId { get; set; }
        public string AlbumName { get; set; }
        public Nullable<decimal> GroupId { get; set; }
        public string AlbumUri { get; set; }
        public string Password { get; set; }
    }
}
