//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialistMeeting
{
    using System;
    using System.Collections.Generic;
    
    public partial class GtmUploadVideoLog
    {
        public int Id { get; set; }
        public string MeetingId { get; set; }
        public Nullable<int> GtmAlbumLogId { get; set; }
        public string Error { get; set; }
        public Nullable<long> ClipId { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public string ClipUri { get; set; }
        public string PathFile { get; set; }
        public string GtmHistoricalMeetingSubject { get; set; }
        public string SessionId { get; set; }
        public Nullable<decimal> WebinarLicenseId { get; set; }
    }
}
