//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialistMeeting
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpecialistMeetingEntities : DbContext
    {
        public SpecialistMeetingEntities()
            : base("name=SpecialistMeetingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GtmAlbumLog> GtmAlbumLog { get; set; }
        public virtual DbSet<GtmUploadVideoLog> GtmUploadVideoLog { get; set; }
    }
}
