//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialistWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumVideos
    {
        public int Id { get; set; }
        public long AlbumId { get; set; }
        public string Videos { get; set; }
        public string Titles { get; set; }
    }
}
