//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialistWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SpecialistWebEntities : DbContext
    {
        public SpecialistWebEntities()
            : base("name=SpecialistWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlbumVideos> AlbumVideos { get; set; }
        public virtual DbSet<Videos> Videos { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> uspGetSeminarGroupsForOneDay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("uspGetSeminarGroupsForOneDay");
        }
    }
}
