//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialistWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videos
    {
        public int VideoID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsActive { get; set; }
        public string YouTubeID { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string LastChanger_TC { get; set; }
        public string Employee_TC { get; set; }
        public int CategoryId { get; set; }
        public bool IsNew { get; set; }
        public string CourseTCList { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<bool> AvailableEveryOne { get; set; }
        public string CourseTCListArchive { get; set; }
    }
}
