//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialistRepl
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SPECREPL_replicatingEntities : DbContext
    {
        public SPECREPL_replicatingEntities()
            : base("name=SPECREPL_replicatingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tCourses> tCourses { get; set; }
        public virtual DbSet<tGroups> tGroups { get; set; }
        public virtual DbSet<tWebinarLicenses> tWebinarLicenses { get; set; }
        public virtual DbSet<tLectures> tLectures { get; set; }
        public virtual DbSet<tComplexes> tComplexes { get; set; }
    }
}
