//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialistRepl
{
    using System;
    using System.Collections.Generic;
    
    public partial class tComplexes
    {
        public string Complex_TC { get; set; }
        public string BranchOffice_TC { get; set; }
        public string Name { get; set; }
        public string Admin_TC { get; set; }
        public string Notes { get; set; }
        public bool IsLocalComplex { get; set; }
        public string Address { get; set; }
        public string SchemeFileName { get; set; }
        public bool IsInUse { get; set; }
        public decimal Complex_ID { get; set; }
        public System.DateTime InputDate { get; set; }
        public string Employee_TC { get; set; }
        public System.DateTime LastChangeDate { get; set; }
        public string LastChanger_TC { get; set; }
        public string AdminEmail { get; set; }
        public string UrlName { get; set; }
        public bool IsPublished { get; set; }
        public string Description { get; set; }
        public string WorkingHours { get; set; }
        public string Metro { get; set; }
        public string PublicPhone { get; set; }
        public string TechEmail { get; set; }
        public string OurOrg_TC { get; set; }
        public string ShortUrl { get; set; }
        public string OfficialName { get; set; }
        public string CxCertPrefix { get; set; }
    }
}
