//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialistRepl
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCourses
    {
        public decimal Course_ID { get; set; }
        public string Course_TC { get; set; }
        public string ParentCourse_TC { get; set; }
        public string ReportsCourse_TC { get; set; }
        public string GruppsSheet { get; set; }
        public string CourseDirection_TC { get; set; }
        public string OurOrg_TC { get; set; }
        public string HostingType_TC { get; set; }
        public string AuthorizationType_TC { get; set; }
        public string CSSClass_TC { get; set; }
        public Nullable<decimal> MaxDiscount { get; set; }
        public Nullable<decimal> OrgPriceCoefficient { get; set; }
        public string Name { get; set; }
        public string NameOfficial { get; set; }
        public string NameOfficialEn { get; set; }
        public string WebName { get; set; }
        public string eLearningName { get; set; }
        public decimal BaseHours { get; set; }
        public decimal AdditionalHours { get; set; }
        public Nullable<decimal> Weeks { get; set; }
        public Nullable<decimal> Days { get; set; }
        public byte NormNumOfStudents { get; set; }
        public byte MaxNumOfStudents { get; set; }
        public int PriceListOrder { get; set; }
        public bool DontShow { get; set; }
        public Nullable<bool> IsTrack { get; set; }
        public bool IsExam { get; set; }
        public bool IsNew { get; set; }
        public Nullable<bool> WebPublishSchedule { get; set; }
        public Nullable<bool> AllowWebOrder { get; set; }
        public bool ProgramAccessible { get; set; }
        public string ProgramURL { get; set; }
        public string ProgramFileName { get; set; }
        public string ProgramTemplate_TC { get; set; }
        public string Prerequisites { get; set; }
        public string PrerequisitesShort { get; set; }
        public string Introduction { get; set; }
        public string WebTopic { get; set; }
        public string WebComment { get; set; }
        public string OnComplete { get; set; }
        public string WebDescription { get; set; }
        public string Picture { get; set; }
        public bool CopyCashPayment { get; set; }
        public bool IsBookkeeperCourse { get; set; }
        public bool BCTC_ContentExists { get; set; }
        public byte BCTC_SeviceExpiresMonths { get; set; }
        public byte BCTC_SeviceExpiresDateBeg { get; set; }
        public string Notes { get; set; }
        public System.DateTime InputDate { get; set; }
        public string Employee_TC { get; set; }
        public System.DateTime LastChangeDate { get; set; }
        public string LastChanger_TC { get; set; }
        public string WebYandexDescription { get; set; }
        public bool IsFeedingCourse { get; set; }
        public string WebShortName { get; set; }
        public string WebNameComment { get; set; }
        public string CourseDirectionA_TC { get; set; }
        public bool IsFreeConsultationExists { get; set; }
        public string CourseTest_TC { get; set; }
        public string InternetSpeed_TC { get; set; }
        public string CourseRequirements { get; set; }
        public bool IsActive { get; set; }
        public bool IsSimple { get; set; }
        public string RatingCourse_TC { get; set; }
        public bool IsPaperQuestionnaire { get; set; }
        public bool IsQuestionnaired { get; set; }
        public string AnnounceDescription { get; set; }
        public string AnnounceImage { get; set; }
        public string QualAdv_TC { get; set; }
        public Nullable<decimal> FeedingPrice { get; set; }
        public bool PriceWithFeeding { get; set; }
        public string UrlName { get; set; }
        public bool IsRestrictedSchedule { get; set; }
        public int WebSortOrder { get; set; }
        public bool IsAllowedHalfCoursePrice { get; set; }
        public bool IsProjectAllowed { get; set; }
        public bool IsPartner { get; set; }
        public bool IsTheory { get; set; }
        public string SoftwareVersion { get; set; }
        public string SoftwareLanguage { get; set; }
        public bool IsNotAuthorized { get; set; }
        public Nullable<decimal> ClassRoomType_ID { get; set; }
        public string WebinarEduURL { get; set; }
        public string WebinarLabsURL { get; set; }
        public decimal WeightCoeff { get; set; }
        public bool IsWebinarRecordExists { get; set; }
        public decimal IntraExtramuralHours { get; set; }
        public string ActualityReason { get; set; }
        public bool IsPaperBookExists { get; set; }
        public bool IsWebinarForbidden { get; set; }
        public bool IsWebinarPlannedForbidden { get; set; }
        public decimal IntraExtramuralHoursOut { get; set; }
        public bool IsUnlimitedTraining { get; set; }
        public Nullable<short> DiscountWebinar { get; set; }
        public string NameCertificate { get; set; }
        public bool IsNotifyEngineers { get; set; }
        public string PlansInfo { get; set; }
        public bool IsDiplProg { get; set; }
        public bool IsOutdated { get; set; }
        public string TechEquipCourseStudent { get; set; }
        public int NormativeQuantity { get; set; }
        public string TeacherMaterialsURL { get; set; }
    }
}
