//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialistRepl
{
    using System;
    using System.Collections.Generic;
    
    public partial class tWebinarLicenses
    {
        public decimal WebinarLicense_ID { get; set; }
        public string LicenseName { get; set; }
        public string LicenseLogin { get; set; }
        public string LicensePassword { get; set; }
        public int SortOrder { get; set; }
        public bool IsVisible { get; set; }
        public string AccessToken { get; set; }
        public Nullable<long> OrganizerKey { get; set; }
    }
}
