//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pioneer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGroups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tGroups()
        {
            this.tGroups1 = new HashSet<tGroups>();
        }
    
        public decimal Group_ID { get; set; }
        public byte[] TS { get; set; }
        public string Color_TC { get; set; }
        public string BranchOffice_TC { get; set; }
        public string Complex_TC { get; set; }
        public string Course_TC { get; set; }
        public string LectureType_TC { get; set; }
        public string DayShift_TC { get; set; }
        public Nullable<System.DateTime> DateBeg { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<System.DateTime> TimeBeg { get; set; }
        public Nullable<System.DateTime> TimeEnd { get; set; }
        public Nullable<System.DateTime> DistDateBeg { get; set; }
        public Nullable<System.DateTime> DistDateEnd { get; set; }
        public Nullable<System.DateTime> LiteratureSent { get; set; }
        public Nullable<System.DateTime> LoginPasswordSent { get; set; }
        public string Teacher_TC { get; set; }
        public string ClassRoom_TC { get; set; }
        public bool IsEmploymentCenter { get; set; }
        public bool ForOvertaking { get; set; }
        public bool SupportingGroup { get; set; }
        public bool IsBlazing { get; set; }
        public bool TeacherIsInformed { get; set; }
        public bool GroupIsInformed { get; set; }
        public decimal Hours { get; set; }
        public decimal HoursAdditional { get; set; }
        public Nullable<decimal> HoursGiven { get; set; }
        public short NumOfStudents { get; set; }
        public short MaxNumOfStudents { get; set; }
        public string DaySequence { get; set; }
        public string DaySequence_TC { get; set; }
        public string Notes { get; set; }
        public string ScheduleHistory { get; set; }
        public string IsCheckedByED { get; set; }
        public string NotesED { get; set; }
        public Nullable<decimal> PaidSum { get; set; }
        public decimal Sequence_ID { get; set; }
        public string ForUpdate { get; set; }
        public System.DateTime InputDate { get; set; }
        public string Employee_TC { get; set; }
        public System.DateTime LastChangeDate { get; set; }
        public string LastChanger_TC { get; set; }
        public Nullable<decimal> BaseGroup_ID { get; set; }
        public bool IsFirstTeachersGroup { get; set; }
        public string Curator_TC { get; set; }
        public bool PrintAnnounce { get; set; }
        public bool WebinarExists { get; set; }
        public bool ForWebinarOnly { get; set; }
        public Nullable<short> Discount { get; set; }
        public bool IsNotUsed4AutoDiscountRules { get; set; }
        public bool IsConfirmedByTeacher { get; set; }
        public Nullable<decimal> MainGroup_ID { get; set; }
        public Nullable<decimal> MegaGroup_ID { get; set; }
        public string WebinarRecordURL { get; set; }
        public string WbnRecLogin { get; set; }
        public string WbnRecPwd { get; set; }
        public bool IsAutoAnnounceDenied { get; set; }
        public bool IsBroadcasting { get; set; }
        public Nullable<short> MaxNumOfWebinarists { get; set; }
        public bool IsIntraExtramural { get; set; }
        public string UrlName { get; set; }
        public bool IsRecordRequired { get; set; }
        public bool IsFixedTeacher { get; set; }
        public bool IsCanceledEnrollment { get; set; }
        public bool IsCompetitorAllowed { get; set; }
        public string OurOrg_TC { get; set; }
        public string RateNoteUO { get; set; }
        public bool IsMinimized { get; set; }
        public Nullable<decimal> Charge { get; set; }
        public bool IsUnwebinared { get; set; }
        public string LegRelType_TC { get; set; }
        public bool IsLecturesConsidered { get; set; }
        public string PresentationSemURL { get; set; }
        public string PromoSemGroupIDs { get; set; }
        public Nullable<decimal> AdvertisingCoeff { get; set; }
        public bool IsForSite { get; set; }
        public string TeamsUrl { get; set; }
        public bool IsDuplicate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGroups> tGroups1 { get; set; }
        public virtual tGroups tGroups2 { get; set; }
    }
}
